api/urls.py
from django.urls import path, include
from api.views import ProductModelViewSet, BasketModelViewSet
from rest_framework import routers


app_name = "api"

router = routers.DefaultRouter()
router.register(r"products", ProductModelViewSet)
router.register(r"basket", BasketModelViewSet)

urlpatterns = [
    path("", include(router.urls)),
]

orders/urls.py
from django.urls import path
from orders.views import OrderCreate


app_name = "orders"

urlpatterns = [
    path("order_create/", OrderCreate.as_view(), name="order_create"),
]

products/urls.py
from django.urls import path

from products.views import (PorductsListView, basket_add,
                            basket_delete)

app_name = "products"

urlpatterns = [
    path("", PorductsListView.as_view(), name="index"),
    path("category/<int:category_id>", PorductsListView.as_view(), name="category"),
    path("basket_add/<int:product_id>", basket_add, name="basket_add"),
    path("basket_delete/<int:basket_id>", basket_delete, name="basket_delete"),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views
from products.views import IndexView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("accounts/", include("allauth.urls")),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("api/", include("api.urls", namespace="api")),
    path("api-token-auth/", views.obtain_auth_token),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, ProfileView, RegisterView,
                         UserLoginView)

app_name = "users"

urlpatterns = [
    path("login", UserLoginView.as_view(), name="login"),
    path("register", RegisterView.as_view(), name="register"),
    path("profile/<int:pk>", login_required(ProfileView.as_view()), name="profile"),
    path("logout", LogoutView.as_view(), name="logout"),
    path("EmailVerification/<str:email>/<uuid:code>/", EmailVerificationView.as_view(), name="EmailVerification"),
]

products/models.py
from django.db import models

from users.models import User


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)
    
    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=12)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to="products_images")
    category = models.ForeignKey("Category", on_delete=models.PROTECT)
    
    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"

    def __str__(self):
        return self.name


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    time_stamp = models.DateTimeField(auto_now_add=True)
    objects = BasketQuerySet.as_manager()

    class Meta:
        verbose_name = "корзина"
        verbose_name_plural = "корзина"

    def __str__(self):
        return f"{self.user.username}, {self.product.name}, {self.quantity}"

    def sum(self):
        return self.product.price * self.quantity

products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.views.generic import ListView, TemplateView

from common.views import TitleMixin
from products.models import Basket, Category, Product


class IndexView(TitleMixin, TemplateView):
    template_name = "products/index.html"
    title = "Store"


# def index(request):
# 	return render(request, "products/index.html")


class PorductsListView(TitleMixin, ListView):
    model = Product
    template_name = "products/products.html"
    paginate_by = 3
    title = "Products"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #  работа с кешем при помощи redis (решил сделать через коммент, т.к. работаю на винде, запарно устанавливать редис)
        # categories = cache.get("categories")
        # if not categories:
        #    context["categories"] = Category.objects.filter( name__in=Product.objects.values("category__name"))
        #    categories = cache.set("categories", context["categories"], 30)
        # else:
        #    context["categories"] = categories
        context["categories"] = Category.objects.filter(
            name__in=Product.objects.values("category__name")
        )
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get("category_id")
        return (
            Product.objects.filter(category_id=category_id) if category_id else queryset
        )


# def products(request, category_id=None, page_number=1):
#     products = (
#         Product.objects.filter(category__id=category_id)
#         if category_id
#         else Product.objects.all()
#     )
#     per_page = 3
#     paginator = Paginator(products, per_page)
#     products_paginator = paginator.page(page_number)
#     context = {
#         "products": products_paginator,
#         "categories": Category.objects.filter(
#             name__in=Product.objects.values("category__name")
#         ),
#     }
#     return render(request, "products/products.html", context)


@login_required
def basket_add(request, product_id):
    product_add = Product.objects.get(id=product_id)
    basket_user = Basket.objects.filter(user=request.user, product=product_add)
    if not basket_user.exists():
        Basket.objects.create(user=request.user, product=product_add, quantity=1)
    else:
        product_basket = Basket.objects.get(user=request.user, product=product_add)
        product_basket.quantity += 1
        product_basket.save()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@login_required
def basket_delete(request, basket_id):
    product_delete = Basket.objects.get(user=request.user, id=basket_id)
    product_delete.delete()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{title}}</title>

    <!-- Bootstrap core CSS -->
    <link href={% static "static/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static "static/vendor/css/index.css" %} rel="stylesheet">
	 {% block css %}
	 {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href={% url "index" %}>Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href={% url "products:index" %}>Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
					 {% if user.is_authenticated %}
					   <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href={% url 'users:profile' user.id %}>Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
								{% if user.is_superuser or user.is_staff %}
                        <li><a class="dropdown-item" href={% url "admin:index" %}>Админ-панель</a></li>
								{% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href={% url "users:logout" %}>
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
					 {% else %}
                <li class="nav-item">
                    <a class="nav-link" href={% url 'users:login' %}>Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
					 {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}
<!-- Bootstrap core JavaScript -->
<script src={% static "static/vendor/jquery/jquery.min.js" %}></script>
<script src={% static "static/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src={% static "static/vendor/fontawesome/fontawesome-icons.js" %} crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/basket.html
{% load humanize %}       
				{% if basket %}
							<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
								Корзина <span class="badge badge-secondary badge-pill">{{basket.total_quantity}}</span>
							</h4>		
							{% for item in basket %}
							<div class="card mb-3">
								<div class="card-body">
									<h5 class="card-title">{{item.product.name}}</h5>
									<p class="card-text">{{item.product.description}}</p>
								</div>
								<ul class="list-group list-group-flush">
									<li class="list-group-item bg-light">
											<div class="row text-center">
												<div class="col-lg-4">
													<div name="basketID" type="number" class="form-control"
																value="{{item.quantity}}" min="0">{{item.quantity}} </div> 
											<!-- тут был input список, но т.к. сумма не коррелирует с изменением количества товаров через него, то пришлось заменить --> 
												</div>
												<div class="col-lg-4">{{item.sum | intcomma}} руб.</div>
												<div class="col-lg-4">
													<a href="{% url "products:basket_delete" item.id %}">
															<i class="fas fa-trash"></i>
													</a>
												</div>
											</div>
									</li>
								</ul>
							</div>
							{% endfor %}
							<div class="card mb-3">
								<div class="card-footer">
									<p class="float-left">Итого</p>
									<h4 class="float-right">{{basket.total_sum | intcomma}} руб.</h4>
								</div>
							</div>
							<a class="btn btn-success btn-lg float-right" href="{% url "orders:order_create" %}">
								Оформить заказ
							</a>
				{% else %}
						<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
							В корзине нет товаров
						</h4>
						
				{% endif %}		

products/templates/products/index.html
{% extends "products/base.html" %}
{% load static %}


{% block css %}
    <!-- Custom styles for this template -->
    <link href={% static "static/vendor/css/index.css"%} rel="stylesheet">
{% endblock %}
{% block content %}
<!-- Page Content -->
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="products.html">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends "products/base.html" %}
{% load static humanize %}


{% block content %}
<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
					<a href="{% url 'products:index' %}" class="list-group-item">Все товары</a>
					{% for category in categories %}
                <a href="{% url 'products:category' category.id %}" class="list-group-item">{{category.name}}</a>
					 {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src={% static "static/vendor/img/slides/slide-1.jpg" %} alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src={% static "static/vendor/img/slides/slide-2.jpg" %} alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src={% static "static/vendor/img/slides/slide-3.jpg" %} alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
					{% for product in page_obj %}

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src={{product.image.url}}
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{product.name}}</a>
                            </h4>
                            <h5>{{product.price | intcomma }}.</h5>
                            <p class="card-text">{{product.description}}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href="{% url 'products:basket_add' product.id %}">Отправить в корзину</a>
                        </div>
                    </div>
                </div>
					{% endfor %}


            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link" href= {% if page_obj.has_previous %} "?page={{page_obj.previous_page_number}}"{% endif %} tabindex="-1" aria-disabled="True">Previous</a>
                    </li>
						  {% for page in page_obj.paginator.page_range %}
						  {% if page == page_obj.number %}
						  <li class="page-item"><span class="page-link" style="color: black" >{{page}}</span></li>
						  {% else %}
						  <li class="page-item"><a class="page-link"  href= "?page={{ page }}">{{page}}</a></li>
						  {% endif %}
						  {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link" href={% if page_obj.has_next %} "?page={{ page_obj.next_page_number }}"{% endif %}>Next</a>
                    </li>
                </ul>
            </nav>
						  
        </div>

    </div>

</div>
<!-- /.container -->
{% endblock %}
{% block footer %}
<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022 </p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}